<?php
$css_config = 
array (
'Skin width, px'=>'940',
'Sidebar width, px'=>'280',
'Primary font size, px'=>'12',
'Font family'=>'Arial, Helvetica, sans-serif',
'H1 font size, px'=>'24',
'H2 font size, px'=>'20',
'H3 font size, px'=>'18',
'Body background color'=>'#FFFFFF',
'Text color'=>'#464032',
'Title color'=>'#221D1D',
'Link color'=>'#651262',
'Link color when hovering'=>'#000000',
'The thickness of the border of the menu, px'=>'3',
'Menu radius, px'=>'11',
'Padding links menu, px'=>'17',
'Menu text color'=>'#FFFFFF',
'Menu font size, px'=>'12',
'Sidebar position'=>'right',
'Sidebar title font size, px'=>'14',
'Sidebar title radius, px'=>'11',
'Sidebar title padding, px'=>'15',
'Start menu gradient color'=>'#B495B5',
'End menu gradient color'=>'#6E146B',
'Start menu gradient color hover'=>'#6E146B',
'End menu gradient color hover'=>'#B495B5',
'Input text color'=>'#333',
'Input text hover color'=>'#000',
'Input border thickness, px'=>'1',
'Input border color'=>'#532050',
'Input border hover color'=>'#480645',
'Input border radius, px'=>'5',
'Input padding, px'=>'3',
'Button start gradient color'=>'#B747B2',
'Button end gradient color'=>'#6E146B',
'Button start gradient color hover'=>'#9D7200',
'Button end gradient color hover'=>'#B5902D',
'Button padding, px'=>'5'
);
?>